### ISSUE TITLE
Use of custom MultiSpeedController instead of WPILib SpeedControllerGroup

### ISSUE THREAD

**Issue by Starlight220** [perSEVERE-5962/robotCode#55]
There seems to be a class of MultiSpeedController in the main package (it shouldn't be there). 
In addition, there is a WPILib SpeedControllerGroup class that is identical to your class, why not use it?

I am reviewing your code as part of the Chop Shop's 2020 Code Review Party.

**Comment by david-lemasurier** [comment]
Hi.  Thank you for the great feedback.  May we ask your team and role?  Thanks!

**Comment by Starlight220** [comment]
I will probably be the lead programmer of 6738 next year.

**Comment by david-lemasurier** [comment]
MultiSpeedController is no longer being used
